<?php

/**
 * BaseStandard
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int       $id                         Type: integer, primary key
 * @property string    $name                       Type: string(255)
 * @property string    $description                Type: clob
 * @property int       $template_id                Type: integer
 * @property double    $weight                     Type: double
 * @property Template  $Template                   
 *  
 * @method int         getId()                     Type: integer, primary key
 * @method string      getName()                   Type: string(255)
 * @method string      getDescription()            Type: clob
 * @method int         getTemplateId()             Type: integer
 * @method double      getWeight()                 Type: double
 * @method Template    getTemplate()               
 *  
 * @method Standard    setId(int $val)             Type: integer, primary key
 * @method Standard    setName(string $val)        Type: string(255)
 * @method Standard    setDescription(string $val) Type: clob
 * @method Standard    setTemplateId(int $val)     Type: integer
 * @method Standard    setWeight(double $val)      Type: double
 * @method Standard    setTemplate(Template $val)  
 *  
 * @package    check-list
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStandard extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('standard');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('template_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('weight', 'double', null, array(
             'type' => 'double',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Template', array(
             'local' => 'template_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}