<?php

/**
 * BaseTemplate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                              $id                                     Type: integer, primary key
 * @property string                           $name                                   Type: string(255)
 * @property string                           $description                            Type: clob
 * @property string                           $prefix                                 Type: string(255)
 * @property int                              $threshold                              Type: integer
 * @property int                              $checklists_qt                          Type: integer
 * @property bool                             $status                                 Type: boolean, default "1"
 * @property Doctrine_Collection|Standard[]   $Standards                              
 * @property Doctrine_Collection|CheckList[]  $CheckLists                             
 *  
 * @method int                                getId()                                 Type: integer, primary key
 * @method string                             getName()                               Type: string(255)
 * @method string                             getDescription()                        Type: clob
 * @method string                             getPrefix()                             Type: string(255)
 * @method int                                getThreshold()                          Type: integer
 * @method int                                getChecklistsQt()                       Type: integer
 * @method bool                               getStatus()                             Type: boolean, default "1"
 * @method Doctrine_Collection|Standard[]     getStandards()                          
 * @method Doctrine_Collection|CheckList[]    getCheckLists()                         
 *  
 * @method Template                           setId(int $val)                         Type: integer, primary key
 * @method Template                           setName(string $val)                    Type: string(255)
 * @method Template                           setDescription(string $val)             Type: clob
 * @method Template                           setPrefix(string $val)                  Type: string(255)
 * @method Template                           setThreshold(int $val)                  Type: integer
 * @method Template                           setChecklistsQt(int $val)               Type: integer
 * @method Template                           setStatus(bool $val)                    Type: boolean, default "1"
 * @method Template                           setStandards(Doctrine_Collection $val)  
 * @method Template                           setCheckLists(Doctrine_Collection $val) 
 *  
 * @package    check-list
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTemplate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('template');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('prefix', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('threshold', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('checklists_qt', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Standard as Standards', array(
             'local' => 'id',
             'foreign' => 'template_id'));

        $this->hasMany('CheckList as CheckLists', array(
             'local' => 'id',
             'foreign' => 'template_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}