<?php

/**
 * AssessmentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssessmentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return AssessmentsTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Assessments');
    }
}