<?php

/**
 * CheckList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 *  
 * @package    check-list
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CheckList extends BaseCheckList
{
  public function getNameWithPrefix()
  {
    $this->getName();
  }

  /**
   * @param $checkListId
   * @return mixed
   */
  public function getCheckListById($checkListId)
  {
    return Doctrine_Core::getTable('CheckList')
      ->getCheckListById($checkListId);
  }

  /**
   * @return mixed
   */
  public function getActiveCheckListInArray($checkListId)
  {
    return Doctrine_Core::getTable('CheckList')->getActiveCheckList(3);
  }

  /**
   * @return mixed
   */
  public function getInactiveCheckListInArray($checkListId)
  {
    return Doctrine_Core::getTable('CheckList')->getInactiveCheckList($checkListId);
  }

  /**
   * @return bool
   */
  public function hasCriteria()
  {
    $criterias = $this->getCheckedStandards();

    if (count($criterias) <= 0)
    {
      return true;
    }

    return false;
  }

  /**
   * @param $checkListId
   * @param int $hydrationMode
   * @return mixed
   */
  public function getAllCriteriasByCheckList($checkListId, $hydrationMode = 2)
  {
    return Doctrine_Core::getTable('CheckList')->getAllCriteriasByCheckList($checkListId, $hydrationMode);
  }
}
