<?php

/**
 * Criteria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 *  
 * @package    check-list
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CheckedStandard extends BaseCheckedStandard
{
  public function getNameCustom()
  {
    return $this->getCheckList()->getPrefix() + '-' + $this->getName();
  }

  /**
   * @param $checkListId
   * @param bool $criterionToExclude
   * @return int
   */
  public static function sumWeightByCheckList($checkListId, $criterionToExclude = false)
  {
    return Doctrine_Core::getTable('CheckedStandard')->sumWeightByCheckList($checkListId, $criterionToExclude);
  }

  /**
   * @param $checkListId
   * @return mixed
   */
  public function getCriteriasByCheckList($checkListId)
  {
    return Doctrine_Core::getTable('CheckedStandard')->getCriteriasByCheckList($checkListId);
  }
}
