Template:
  actAs:
    Timestampable: ~
  columns:
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    description:
      type: clob
    prefix:
      type: string(255)
    threshold:
      type: integer
      notnull: true
    checklists_qt:
      type: integer
    status:
      type: boolean
      default: true
      notnull: true

Standard:
  actAs:
    Timestampable: ~
  columns:
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    description:
      type: clob
    template_id:
      type: integer
      notnull: true
    weight:
      type: double
  relations:
    Template:
      onDelete: CASCADE
      local: template_id
      foreign: id
      foreignAlias: Standards

CheckList:
  actAs:
    Timestampable: ~
  columns:
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    observations:
      type: clob
    reference:
      type: string(255)
    template_id:
      type: integer
      notnull: true
    responsible_id:
      type: integer
      notnull: true
    original_threshold:
      type: integer
      notnull: true
    assessment:
      type: float
    status:
      type: boolean
      default: true
      notnull: true
    version_at:
      type: timestamp
  relations:
    Template:
      class: Template
      local: template_id
      foreign: id
      foreignAlias: CheckLists
    Responsible:
      class: sfGuardUser
      local: responsible_id
      foreign: id
      foreignAlias: CheckLists

CheckedStandard:
  actAs:
    Timestampable: ~
  columns:
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    description:
      type: clob
    standard_type:
      type: string(255)
    checklist_id:
      type: integer
      notnull: true
    final_weight:
      type: double
    option_selected:
      type: string(255)
    assigned_value:
      type: double
  relations:
    CheckList:
      onDelete: CASCADE
      local: checklist_id
      foreign: id
      foreignAlias: CheckedStandards

Assessments:
  actAs:
    Timestampable: ~
  columns:
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    checklist_id:
      type: integer
      notnull: true
    reference:
      type: string(255)
      notnull: true
    day:
      type: int
    month:
      type: int
    year:
      type: int
    day_of_week:
      type: string
    version_at:
      type: timestamp
      notnull: true
    value:
      type: double
      notnull: true
  relations:
    CheckList:
      class: CheckList
      onDelete: CASCADE
      local: checklist_id
      foreign: id
      foreignAlias: Assessments